# Generated by Django 2.2.4 on 2019-10-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nginx',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('launch_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedELK',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('launch_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nginx_AWS',
            fields=[
                ('nginx_aws_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='delivery.Nginx')),
                ('aws_id', models.CharField(max_length=50)),
                ('dns_public_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedELK_AWS',
            fields=[
                ('redelk_aws_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='delivery.RedELK')),
                ('aws_id', models.CharField(max_length=50)),
                ('dns_public_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedELK_Local',
            fields=[
                ('redelk_local_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='delivery.RedELK')),
                ('kibana_access', models.GenericIPAddressField()),
                ('listener_port', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Infra',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nginx_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.Nginx')),
                ('redelk_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.RedELK')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
