from django.http import *
from django.template.response import TemplateResponse
from django.shortcuts import redirect
from pyattck import Attck

def index(request):
	#return HttpResponse(str(request.__dict__))
	return HttpResponseNotFound("Erreur fichier introuvable")

def dashboard(request):
	"""matrix = {
		"Initial Access":{"Drive-by Compromise", "Exploit Public-Facing Application", "External Remote Services", "Hardware Additions", "Replication Through Removable Media", "Spearphishing Attachment", "Spearphishing Link", "Spearphishing via Service", "Supply Chain Compromise", "Trusted Relationship", "Valid Accounts"},
		"Execution":{"AppleScript", "CMSTP", "Command-Line Interface", "Compiled HTML File", "Control Panel Items", "Dynamic Data Exchange", "Execution through API", "Execution through Module Load", "Exploitation for Client Execution", "Graphical User Interface", "InstallUtil", "Launchctl", "Local Job Scheduling", "LSASS Driver", "Mshta", "PowerShell", "Regsvcs/Regasm", "Regsvr32", "Rundll32", "Scheduled Task", "Scripting", "Service Execution", "Signed Binary Proxy Execution", "Signed Script Proxy Execution", "Source", "Space after Filename", "Third-party Software", "Trap", "Trusted Developer Utilities", "User Execution", "Windows Management Instrumentation", "Windows Remote Management", "XSL Script Processing"},
		"Persistence":{".bash_profile and .bashrc", "Accessibility Features", "Account Manipulation", "AppCert DLLs", "AppInit DLLs", "Application Shimming", "Authentication Package", "BITS Jobs", "Bootkit", "Browser Extensions", "Change Default File Association", "Component Firmware", "Component Object Model Hijacking", "Create Account", "DLL Search Order Hijacking", "Dylib Hijacking", "External Remote Services", "File System Permissions Weakness", "Hidden Files and Directories", "Hooking", "Hypervisor", "Image File Execution Options Injection", "Kernel Modules and Extensions", "Launch Agent", "Launch Daemon", "Launchctl", "LC_LOAD_DYLIB Addition", "Local Job Scheduling", "Login Item", "Logon Scripts", "LSASS Driver", "Modify Existing Service", "Netsh Helper DLL", "New Service", "Office Application Startup", "Path Interception", "Plist Modification", "Port Knocking", "Port Monitors", "Rc.common", "Re-opened Applications", "Redundant Access", "Registry Run Keys / Startup Folder", "Scheduled Task", "Screensaver", "Security Support Provider", "Service Registry Permissions Weakness", "Setuid and Setgid", "Shortcut Modification", "SIP and Trust Provider Hijacking", "Startup Items", "System Firmware", "Systemd Service", "Time Providers", "Trap", "Valid Accounts", "Web Shell", "Windows Management Instrumentation Event Subscription", "Winlogon Helper DLL"},
		"Privilege Escalation":{"Access Token Manipulation", "Accessibility Features", "AppCert DLLs", "AppInit DLLs", "Application Shimming", "Bypass User Account Control", "DLL Search Order Hijacking", "Dylib Hijacking", "Exploitation for Privilege Escalation", "Extra Window Memory Injection", "File System Permissions Weakness", "Hooking", "Image File Execution Options Injection", "Launch Daemon", "New Service", "Path Interception", "Plist Modification", "Port Monitors", "Process Injection", "Scheduled Task", "Service Registry Permissions Weakness", "Setuid and Setgid", "SID-History Injection", "Startup Items", "Sudo", "Sudo Caching", "Valid Accounts", "Web Shell"},
		"Defense Evasion":{"Access Token Manipulation", "Binary Padding", "BITS Jobs", "Bypass User Account Control", "Clear Command History", "CMSTP", "Code Signing", "Compile After Delivery", "Compiled HTML File", "Component Firmware", "Component Object Model Hijacking", "Control Panel Items", "DCShadow", "Deobfuscate/Decode Files or Information", "Disabling Security Tools", "DLL Search Order Hijacking", "DLL Side-Loading", "Execution Guardrails", "Exploitation for Defense Evasion", "Extra Window Memory Injection", "File Deletion", "File Permissions Modification", "File System Logical Offsets", "Gatekeeper Bypass", "Group Policy Modification", "Hidden Files and Directories", "Hidden Users", "Hidden Window", "HISTCONTROL", "Image File Execution Options Injection", "Indicator Blocking", "Indicator Removal from Tools", "Indicator Removal on Host", "Indirect Command Execution", "Install Root Certificate", "InstallUtil", "Launchctl", "LC_MAIN Hijacking", "Masquerading", "Modify Registry", "Mshta", "Network Share Connection Removal", "NTFS File Attributes", "Obfuscated Files or Information", "Plist Modification", "Port Knocking", "Process Doppelgänging", "Process Hollowing", "Process Injection", "Redundant Access", "Regsvcs/Regasm", "Regsvr32", "Rootkit", "Rundll32", "Scripting", "Signed Binary Proxy Execution", "Signed Script Proxy Execution", "SIP and Trust Provider Hijacking", "Software Packing", "Space after Filename", "Template Injection", "Timestomp", "Trusted Developer Utilities", "Valid Accounts", "Virtualization/Sandbox Evasion", "Web Service", "XSL Script Processing"},
		"Credential Access":{"Account Manipulation", "Bash History", "Brute Force", "Credential Dumping", "Credentials in Files", "Credentials in Registry", "Exploitation for Credential Access", "Forced Authentication", "Hooking", "Input Capture", "Input Prompt", "Kerberoasting", "Keychain", "LLMNR/NBT-NS Poisoning and Relay", "Network Sniffing", "Password Filter DLL", "Private Keys", "Securityd Memory", "Two-Factor Authentication Interception"},
		"Discovery":{"Account Discovery", "Application Window Discovery", "Browser Bookmark Discovery", "Domain Trust Discovery", "File and Directory Discovery", "Network Service Scanning", "Network Share Discovery", "Network Sniffing", "Password Policy Discovery", "Peripheral Device Discovery", "Permission Groups Discovery", "Process Discovery", "Query Registry", "Remote System Discovery", "Security Software Discovery", "System Information Discovery", "System Network Configuration Discovery", "System Network Connections Discovery", "System Owner/User Discovery", "System Service Discovery", "System Time Discovery", "Virtualization/Sandbox Evasion"},
		"Lateral Movement":{"AppleScript", "Application Deployment Software", "Distributed Component Object Model", "Exploitation of Remote Services", "Logon Scripts", "Pass the Hash", "Pass the Ticket", "Remote Desktop Protocol", "Remote File Copy", "Remote Services", "Replication Through Removable Media", "Shared Webroot", "SSH Hijacking", "Taint Shared Content", "Third-party Software", "Windows Admin Shares", "Windows Remote Management"},
		"Collection":{"Audio Capture", "Automated Collection", "Clipboard Data", "Data from Information Repositories", "Data from Local System", "Data from Network Shared Drive", "Data from Removable Media", "Data Staged", "Email Collection", "Input Capture", "Man in the Browser", "Screen Capture", "Video Capture"},
		"Command And Control":{"Commonly Used Port", "Communication Through Removable Media", "Connection Proxy", "Custom Command and Control Protocol", "Custom Cryptographic Protocol", "Data Encoding", "Data Obfuscation", "Domain Fronting", "Domain Generation Algorithms", "Fallback Channels", "Multi-hop Proxy", "Multi-Stage Channels", "Multiband Communication", "Multilayer Encryption", "Port Knocking", "Remote Access Tools", "Remote File Copy", "Standard Application Layer Protocol", "Standard Cryptographic Protocol", "Standard Non-Application Layer Protocol", "Uncommonly Used Port", "Web Service"},
		"Exfiltration":{"Automated Exfiltration", "Data Compressed", "Data Encrypted", "Data Transfer Size Limits", "Exfiltration Over Alternative Protocol", "Exfiltration Over Command and Control Channel", "Exfiltration Over Other Network Medium", "Exfiltration Over Physical Medium", "Scheduled Transfer"},
		"Impact":{"Data Destruction", "Data Encrypted for Impact", "Defacement", "Disk Content Wipe", "Disk Structure Wipe", "Endpoint Denial of Service", "Firmware Corruption", "Inhibit System Recovery", "Network Denial of Service", "Resource Hijacking", "Runtime Data Manipulation", "Service Stop", "Stored Data Manipulation", "Transmitted Data Manipulation"}
	}
	"""
	matrix = {
	  "data":{
	   "Initial Access":[
	      "Drive-by Compromise",
	      "Exploit Public-Facing Application",
	      "External Remote Services",
	      "Hardware Additions",
	      "Replication Through Removable Media",
	      "Spearphishing Attachment",
	      "Spearphishing Link",
	      "Spearphishing via Service",
	      "Supply Chain Compromise",
	      "Trusted Relationship",
	      "Valid Accounts"
	   ],
	   "Execution":[
	      "AppleScript",
	      "CMSTP",
	      "Command-Line Interface",
	      "Compiled HTML File",
	      "Control Panel Items",
	      "Dynamic Data Exchange",
	      "Execution through API",
	      "Execution through Module Load",
	      "Exploitation for Client Execution",
	      "Graphical User Interface",
	      "InstallUtil",
	      "Launchctl",
	      "Local Job Scheduling",
	      "LSASS Driver",
	      "Mshta",
	      "PowerShell",
	      "Regsvcs/Regasm",
	      "Regsvr32",
	      "Rundll32",
	      "Scheduled Task",
	      "Scripting",
	      "Service Execution",
	      "Signed Binary Proxy Execution",
	      "Signed Script Proxy Execution",
	      "Source",
	      "Space after Filename",
	      "Third-party Software",
	      "Trap",
	      "Trusted Developer Utilities",
	      "User Execution",
	      "Windows Management Instrumentation",
	      "Windows Remote Management",
	      "XSL Script Processing"
	   ],
	   "Persistence":[
	      ".bash_profile and .bashrc",
	      "Accessibility Features",
	      "Account Manipulation",
	      "AppCert DLLs",
	      "AppInit DLLs",
	      "Application Shimming",
	      "Authentication Package",
	      "BITS Jobs",
	      "Bootkit",
	      "Browser Extensions",
	      "Change Default File Association",
	      "Component Firmware",
	      "Component Object Model Hijacking",
	      "Create Account",
	      "DLL Search Order Hijacking",
	      "Dylib Hijacking",
	      "External Remote Services",
	      "File System Permissions Weakness",
	      "Hidden Files and Directories",
	      "Hooking",
	      "Hypervisor",
	      "Image File Execution Options Injection",
	      "Kernel Modules and Extensions",
	      "Launch Agent",
	      "Launch Daemon",
	      "Launchctl",
	      "LC_LOAD_DYLIB Addition",
	      "Local Job Scheduling",
	      "Login Item",
	      "Logon Scripts",
	      "LSASS Driver",
	      "Modify Existing Service",
	      "Netsh Helper DLL",
	      "New Service",
	      "Office Application Startup",
	      "Path Interception",
	      "Plist Modification",
	      "Port Knocking",
	      "Port Monitors",
	      "Rc.common",
	      "Re-opened Applications",
	      "Redundant Access",
	      "Registry Run Keys / Startup Folder",
	      "Scheduled Task",
	      "Screensaver",
	      "Security Support Provider",
	      "Service Registry Permissions Weakness",
	      "Setuid and Setgid",
	      "Shortcut Modification",
	      "SIP and Trust Provider Hijacking",
	      "Startup Items",
	      "System Firmware",
	      "Systemd Service",
	      "Time Providers",
	      "Trap",
	      "Valid Accounts",
	      "Web Shell",
	      "Windows Management Instrumentation Event Subscription",
	      "Winlogon Helper DLL"
	   ],
	   "Privilege Escalation":[
	      "Access Token Manipulation",
	      "Accessibility Features",
	      "AppCert DLLs",
	      "AppInit DLLs",
	      "Application Shimming",
	      "Bypass User Account Control",
	      "DLL Search Order Hijacking",
	      "Dylib Hijacking",
	      "Exploitation for Privilege Escalation",
	      "Extra Window Memory Injection",
	      "File System Permissions Weakness",
	      "Hooking",
	      "Image File Execution Options Injection",
	      "Launch Daemon",
	      "New Service",
	      "Path Interception",
	      "Plist Modification",
	      "Port Monitors",
	      "Process Injection",
	      "Scheduled Task",
	      "Service Registry Permissions Weakness",
	      "Setuid and Setgid",
	      "SID-History Injection",
	      "Startup Items",
	      "Sudo",
	      "Sudo Caching",
	      "Valid Accounts",
	      "Web Shell"
	   ],
	   "Defense Evasion":[
	      "Access Token Manipulation",
	      "Binary Padding",
	      "BITS Jobs",
	      "Bypass User Account Control",
	      "Clear Command History",
	      "CMSTP",
	      "Code Signing",
	      "Compile After Delivery",
	      "Compiled HTML File",
	      "Component Firmware",
	      "Component Object Model Hijacking",
	      "Control Panel Items",
	      "DCShadow",
	      "Deobfuscate/Decode Files or Information",
	      "Disabling Security Tools",
	      "DLL Search Order Hijacking",
	      "DLL Side-Loading",
	      "Execution Guardrails",
	      "Exploitation for Defense Evasion",
	      "Extra Window Memory Injection",
	      "File Deletion",
	      "File Permissions Modification",
	      "File System Logical Offsets",
	      "Gatekeeper Bypass",
	      "Group Policy Modification",
	      "Hidden Files and Directories",
	      "Hidden Users",
	      "Hidden Window",
	      "HISTCONTROL",
	      "Image File Execution Options Injection",
	      "Indicator Blocking",
	      "Indicator Removal from Tools",
	      "Indicator Removal on Host",
	      "Indirect Command Execution",
	      "Install Root Certificate",
	      "InstallUtil",
	      "Launchctl",
	      "LC_MAIN Hijacking",
	      "Masquerading",
	      "Modify Registry",
	      "Mshta",
	      "Network Share Connection Removal",
	      "NTFS File Attributes",
	      "Obfuscated Files or Information",
	      "Plist Modification",
	      "Port Knocking",
	      "Process Doppelgänging",
	      "Process Hollowing",
	      "Process Injection",
	      "Redundant Access",
	      "Regsvcs/Regasm",
	      "Regsvr32",
	      "Rootkit",
	      "Rundll32",
	      "Scripting",
	      "Signed Binary Proxy Execution",
	      "Signed Script Proxy Execution",
	      "SIP and Trust Provider Hijacking",
	      "Software Packing",
	      "Space after Filename",
	      "Template Injection",
	      "Timestomp",
	      "Trusted Developer Utilities",
	      "Valid Accounts",
	      "Virtualization/Sandbox Evasion",
	      "Web Service",
	      "XSL Script Processing"
	   ],
	   "Credential Access":[
	      "Account Manipulation",
	      "Bash History",
	      "Brute Force",
	      "Credential Dumping",
	      "Credentials in Files",
	      "Credentials in Registry",
	      "Exploitation for Credential Access",
	      "Forced Authentication",
	      "Hooking",
	      "Input Capture",
	      "Input Prompt",
	      "Kerberoasting",
	      "Keychain",
	      "LLMNR/NBT-NS Poisoning and Relay",
	      "Network Sniffing",
	      "Password Filter DLL",
	      "Private Keys",
	      "Securityd Memory",
	      "Two-Factor Authentication Interception"
	   ],
	   "Discovery":[
	      "Account Discovery",
	      "Application Window Discovery",
	      "Browser Bookmark Discovery",
	      "Domain Trust Discovery",
	      "File and Directory Discovery",
	      "Network Service Scanning",
	      "Network Share Discovery",
	      "Network Sniffing",
	      "Password Policy Discovery",
	      "Peripheral Device Discovery",
	      "Permission Groups Discovery",
	      "Process Discovery",
	      "Query Registry",
	      "Remote System Discovery",
	      "Security Software Discovery",
	      "System Information Discovery",
	      "System Network Configuration Discovery",
	      "System Network Connections Discovery",
	      "System Owner/User Discovery",
	      "System Service Discovery",
	      "System Time Discovery",
	      "Virtualization/Sandbox Evasion"
	   ],
	   "Lateral Movement":[
	      "AppleScript",
	      "Application Deployment Software",
	      "Distributed Component Object Model",
	      "Exploitation of Remote Services",
	      "Logon Scripts",
	      "Pass the Hash",
	      "Pass the Ticket",
	      "Remote Desktop Protocol",
	      "Remote File Copy",
	      "Remote Services",
	      "Replication Through Removable Media",
	      "Shared Webroot",
	      "SSH Hijacking",
	      "Taint Shared Content",
	      "Third-party Software",
	      "Windows Admin Shares",
	      "Windows Remote Management"
	   ],
	   "Collection":[
	      "Audio Capture",
	      "Automated Collection",
	      "Clipboard Data",
	      "Data from Information Repositories",
	      "Data from Local System",
	      "Data from Network Shared Drive",
	      "Data from Removable Media",
	      "Data Staged",
	      "Email Collection",
	      "Input Capture",
	      "Man in the Browser",
	      "Screen Capture",
	      "Video Capture"
	   ],
	   "Command And Control":[
	      "Commonly Used Port",
	      "Communication Through Removable Media",
	      "Connection Proxy",
	      "Custom Command and Control Protocol",
	      "Custom Cryptographic Protocol",
	      "Data Encoding",
	      "Data Obfuscation",
	      "Domain Fronting",
	      "Domain Generation Algorithms",
	      "Fallback Channels",
	      "Multi-hop Proxy",
	      "Multi-Stage Channels",
	      "Multiband Communication",
	      "Multilayer Encryption",
	      "Port Knocking",
	      "Remote Access Tools",
	      "Remote File Copy",
	      "Standard Application Layer Protocol",
	      "Standard Cryptographic Protocol",
	      "Standard Non-Application Layer Protocol",
	      "Uncommonly Used Port",
	      "Web Service"
	   ],
	   "Exfiltration":[
	      "Automated Exfiltration",
	      "Data Compressed",
	      "Data Encrypted",
	      "Data Transfer Size Limits",
	      "Exfiltration Over Alternative Protocol",
	      "Exfiltration Over Command and Control Channel",
	      "Exfiltration Over Other Network Medium",
	      "Exfiltration Over Physical Medium",
	      "Scheduled Transfer"
	   ],
	   "Impact":[
	      "Data Destruction",
	      "Data Encrypted for Impact",
	      "Defacement",
	      "Disk Content Wipe",
	      "Disk Structure Wipe",
	      "Endpoint Denial of Service",
	      "Firmware Corruption",
	      "Inhibit System Recovery",
	      "Network Denial of Service",
	      "Resource Hijacking",
	      "Runtime Data Manipulation",
	      "Service Stop",
	      "Stored Data Manipulation",
	      "Transmitted Data Manipulation"
	   ]
		}
	}

	for step in matrix["data"]:
		print(step) #OK
		#print(matrix[step]) #OK
	return TemplateResponse(request, 'dashboard.html', {"data": matrix["data"]})

def home(request):
	#return TemplateResponse(request, 'base.html', {'name': 'charlou'})
	return TemplateResponse(request, 'home.html')

def redirect_root(request):
    response = redirect('/login/')
    return response